- name: app setup
  include_role:
    name: common
    tasks_from: app_setup
- name: python
  include_role:
    name: common
    tasks_from: python

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd

