- name: installing mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: present
- name: enable and start mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
- name: modifying the root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}