- name: app setup
  include_role:
    name: common
    tasks_from: app_setup
- name: nodejs
  include_role:
    name: common
    tasks_from: nodejs
-



- name: copying the mongodb repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: installing mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present
- name: checking the products loaded or not
  ansible.builtin.command: mongosh --host mongodb.prasannadevops.online --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
- name: printing the catalogue catalogue_output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
- name: loading the products
  ansible.builtin.shell: mongosh --host mongodb.prasannadevops.online </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: systemd
  include_role:
    name: common
    tasks_from: systemd